version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm install
      - npm install lodash --save
      - npm update
  build:
    commands:
      - echo "Build completed successfully!"
   post_build:
    commands:
      - echo "Build completed successfully!"


