version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm init
      - npm install
      - npm install lodash --save
      - npm update
      - npm run package.json
      - npm start
  build:
    commands:
      - npm test

